// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/menu-variants/CandyKingdom.tsx": () => import("../components/mockups/menu-variants/CandyKingdom.tsx"),
  "./components/mockups/menu-variants/StarlightQuest.tsx": () => import("../components/mockups/menu-variants/StarlightQuest.tsx"),
  "./components/mockups/menu-variants/SunshineAdventure.tsx": () => import("../components/mockups/menu-variants/SunshineAdventure.tsx")
};
