// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/menu-variants/CandyKingdom.tsx": () => import("../components/mockups/menu-variants/CandyKingdom.tsx"),
  "./components/mockups/menu-variants/FractionBarStack.tsx": () => import("../components/mockups/menu-variants/FractionBarStack.tsx"),
  "./components/mockups/menu-variants/Layout1Hero.tsx": () => import("../components/mockups/menu-variants/Layout1Hero.tsx"),
  "./components/mockups/menu-variants/Layout2Horizon.tsx": () => import("../components/mockups/menu-variants/Layout2Horizon.tsx"),
  "./components/mockups/menu-variants/Layout3GameCard.tsx": () => import("../components/mockups/menu-variants/Layout3GameCard.tsx"),
  "./components/mockups/menu-variants/NumberLineQuest.tsx": () => import("../components/mockups/menu-variants/NumberLineQuest.tsx"),
  "./components/mockups/menu-variants/PieChartMenu.tsx": () => import("../components/mockups/menu-variants/PieChartMenu.tsx"),
  "./components/mockups/menu-variants/StarlightQuest.tsx": () => import("../components/mockups/menu-variants/StarlightQuest.tsx"),
  "./components/mockups/menu-variants/SunshineAdventure.tsx": () => import("../components/mockups/menu-variants/SunshineAdventure.tsx"),
  "./components/mockups/level-screen/LevelScreen.tsx": () => import("../components/mockups/level-screen/LevelScreen.tsx")
};
